<?php
use Drupal\field\FieldStorageConfigInterface;
use Drupal\views\Plugin\views\cache\CachePluginBase;
use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\query\Sql;


function custom_views_query_alter(ViewExecutable $view, \Drupal\views\Plugin\views\query\QueryPluginBase $query) {
  $current_path = \Drupal::service('path.current')->getPath();
  $path_args = explode('/', $current_path);

  if ($view->id() == 'home_image_slider' && $view->getDisplay()->display['id'] == 'block_2') {
    // $nid = $path_args[2];   //getting node id e.g., localhost/slide_shoeD8/node/10
    // $node = node_load($nid);
    // $tid = $node->field_slider_type->getValue();
// print($slider_target_id);
// print_r($query->where);
    // $query->where[0]['conditions'][0]['value'][':taxonomy_index_tid'] = $tid;
    // $query->where[0]['conditions'][0]['operator'] = '=';
  }
}
